name: htmltopdf
on: [push]
jobs:
  build-project:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: 14.17.0
      - run: node -v